queue_test: queue_test.o queue.o timer.o
	g++ queue_test.o queue.o timer.o -o queue_test
queue_test.o:
	g++ -c queue_test.cc -o queue_test.o
queue.o:
	g++ -c queue.cc -o queue.o
timer.o:
	gcc -c timer.c -o timer.o
clean:
	rm -f *.o
